// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGC.Datos;

#nullable disable

namespace SGC.Datos.Migrations
{
    [DbContext(typeof(SGCContext))]
    [Migration("20260922142648_InicialSGC")]
    partial class InicialSGC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicoObraSocial", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("ObrasSocialesAceptadasId")
                        .HasColumnType("int");

                    b.HasKey("MedicoId", "ObrasSocialesAceptadasId");

                    b.HasIndex("ObrasSocialesAceptadasId");

                    b.ToTable("MedicoObraSocial", (string)null);
                });

            modelBuilder.Entity("MedicoUsuario", b =>
                {
                    b.Property<int>("MedicosAsignadosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MedicosAsignadosId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioMedico", (string)null);
                });

            modelBuilder.Entity("SGC.Entidades.ActividadMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Procedimiento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecetaMedicamentos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoActividadId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoActividadId");

                    b.HasIndex("TurnoId")
                        .IsUnique();

                    b.ToTable("ActividadesMedicas", t =>
                        {
                            t.HasCheckConstraint("CK_ActividadMedica_Motivo", "LEN(MotivoConsulta) > 0");
                        });
                });

            modelBuilder.Entity("SGC.Entidades.AgendaMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "DiaSemana", "HoraInicio", "HoraFin")
                        .IsUnique();

                    b.ToTable("AgendasMedico", t =>
                        {
                            t.HasCheckConstraint("CK_AgendaMedico_Rango", "HoraFin > HoraInicio");
                        });
                });

            modelBuilder.Entity("SGC.Entidades.ExcepcionAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("ExcepcionesAgenda", t =>
                        {
                            t.HasCheckConstraint("CK_ExcepcionAgenda_Tipo", "(Tipo = 0 AND HoraInicio IS NULL AND HoraFin IS NULL) OR (Tipo = 1 AND HoraInicio IS NOT NULL AND HoraFin IS NOT NULL AND HoraFin > HoraInicio)");
                        });
                });

            modelBuilder.Entity("SGC.Entidades.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("PrecioConsultaParticular")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Medicos", t =>
                        {
                            t.HasCheckConstraint("CK_Medico_Precio", "PrecioConsultaParticular >= 0");
                        });
                });

            modelBuilder.Entity("SGC.Entidades.ObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PorcentajeCobertura")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ObrasSociales", t =>
                        {
                            t.HasCheckConstraint("CK_ObraSocial_Porcentaje", "PorcentajeCobertura BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("SGC.Entidades.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("ObraSocialId");

                    b.ToTable("Pacientes", t =>
                        {
                            t.HasCheckConstraint("CK_Paciente_FechaNacimiento", "FechaNacimiento <= CAST(GETDATE() AS DATE)");
                        });
                });

            modelBuilder.Entity("SGC.Entidades.TipoActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionSugeridaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("NombreTipo")
                        .IsUnique();

                    b.ToTable("TiposActividad", t =>
                        {
                            t.HasCheckConstraint("CK_TipoActividad_Duracion", "DuracionSugeridaMinutos > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Atencion clinica de rutina o primera vez",
                            DuracionSugeridaMinutos = 30,
                            NombreTipo = "Consulta General"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Control periodico o post-tratamiento",
                            DuracionSugeridaMinutos = 30,
                            NombreTipo = "Control / Seguimiento"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Realizacion o evaluacion de estudios clinicos",
                            DuracionSugeridaMinutos = 45,
                            NombreTipo = "Estudio / Practica"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Emision o renovacion de recetas farmacologicas",
                            DuracionSugeridaMinutos = 20,
                            NombreTipo = "Receta / Prescripcion"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Emision de apto fisico o certificado medico",
                            DuracionSugeridaMinutos = 20,
                            NombreTipo = "Certificado Medico"
                        });
                });

            modelBuilder.Entity("SGC.Entidades.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("MedioPago")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Turnos", t =>
                        {
                            t.HasCheckConstraint("CK_Turno_Duracion", "DuracionMinutos > 0");

                            t.HasCheckConstraint("CK_Turno_Monto", "Monto IS NULL OR Monto >= 0");
                        });
                });

            modelBuilder.Entity("SGC.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_MedicoUnico")
                        .HasFilter("[Rol] = 2");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_RolMedico", "Rol <> 2 OR MedicoId IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MedicoObraSocial", b =>
                {
                    b.HasOne("SGC.Entidades.Medico", null)
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGC.Entidades.ObraSocial", null)
                        .WithMany()
                        .HasForeignKey("ObrasSocialesAceptadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicoUsuario", b =>
                {
                    b.HasOne("SGC.Entidades.Medico", null)
                        .WithMany()
                        .HasForeignKey("MedicosAsignadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGC.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGC.Entidades.ActividadMedica", b =>
                {
                    b.HasOne("SGC.Entidades.TipoActividad", "TipoActividad")
                        .WithMany()
                        .HasForeignKey("TipoActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGC.Entidades.Turno", "Turno")
                        .WithOne("ActividadMedica")
                        .HasForeignKey("SGC.Entidades.ActividadMedica", "TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoActividad");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SGC.Entidades.AgendaMedico", b =>
                {
                    b.HasOne("SGC.Entidades.Medico", "Medico")
                        .WithMany("Agenda")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SGC.Entidades.ExcepcionAgenda", b =>
                {
                    b.HasOne("SGC.Entidades.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SGC.Entidades.Paciente", b =>
                {
                    b.HasOne("SGC.Entidades.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("SGC.Entidades.Turno", b =>
                {
                    b.HasOne("SGC.Entidades.Medico", "Medico")
                        .WithMany("Turnos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGC.Entidades.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SGC.Entidades.Usuario", b =>
                {
                    b.HasOne("SGC.Entidades.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SGC.Entidades.Medico", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SGC.Entidades.Paciente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SGC.Entidades.Turno", b =>
                {
                    b.Navigation("ActividadMedica");
                });
#pragma warning restore 612, 618
        }
    }
}
